spring:
  application:
    name: dashflow
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  main:
    allow-bean-definition-overriding: true
server:
  error:
    include-message: always
  servlet:
    context-path: /web-server
logging:
  level:
    org:
      springframework: DEBUG
      apache:
              tomcat: DEBUG
              catalina: DEBUG