spring:
  application:
    name: dashflow
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/oracle
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/dashflow-db-versioning

jira:
  email: ${JIRA_EMAIL}
  token: ${JIRA_TOKEN}

server:
  error:
    include-message: always