databaseType = "PostgreSql"
id = "3240e193-1479-4fdb-ad47-f381d4e89c28"
name = "dashflow-db-versioning"

[flyway]
locations = [ "filesystem:migration" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:postgresql://localhost:5432/postgres"
user = "postgres"
password = "postgres"
schemas = [ "public", "dw_dashflow", "dashflow_appl" ]

defaultSchema = "public"
