-- Create the schema (user) for the application - run as privileged user
-- CREATE USER dashflow_appl IDENTIFIED BY password
--     DEFAULT TABLESPACE users
-- TEMPORARY TABLESPACE temp
-- QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO dashflow_appl;

-- USERS TABLE
CREATE TABLE dashflow_appl.users (
                                     user_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                     username VARCHAR2(60) NOT NULL,
                                     password VARCHAR2(255) NOT NULL,
                                     email VARCHAR2(100) NOT NULL,
                                     created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
                                     CONSTRAINT uk_users_username UNIQUE (username),
                                     CONSTRAINT uk_users_email UNIQUE (email)
);

-- TOOLS TABLE
CREATE TABLE dashflow_appl.tools (
                                     tool_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                     tool_name VARCHAR2(255) NOT NULL
);

-- ACCOUNTS TABLE
CREATE TABLE dashflow_appl.accounts (
                                        account VARCHAR2(255),
                                        user_id NUMBER,
                                        tool_id NUMBER,
                                        CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES dashflow_appl.users(user_id) ON DELETE CASCADE,
                                        CONSTRAINT fk_accounts_tool FOREIGN KEY (tool_id) REFERENCES dashflow_appl.tools(tool_id) ON DELETE CASCADE,
                                        CONSTRAINT uk_accounts_user_tool UNIQUE (user_id, tool_id)
);

-- ROLES TABLE
CREATE TABLE dashflow_appl.roles (
                                     role_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                     role_name VARCHAR2(60) NOT NULL,
                                     CONSTRAINT uk_roles_name UNIQUE (role_name)
);

-- PERMISSIONS TABLE
CREATE TABLE dashflow_appl.permissions (
                                           permission_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                           permission_name VARCHAR2(100) NOT NULL,
                                           description VARCHAR2(255),
                                           CONSTRAINT uk_permissions_name UNIQUE (permission_name)
);

-- USER_ROLES BRIDGE TABLE
CREATE TABLE dashflow_appl.user_roles (
                                          user_id NUMBER,
                                          role_id NUMBER,
                                          CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
                                          CONSTRAINT fk_user_roles_users FOREIGN KEY (user_id) REFERENCES dashflow_appl.users(user_id) ON DELETE CASCADE,
                                          CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES dashflow_appl.roles(role_id) ON DELETE CASCADE
);

-- ROLE_PERMISSIONS BRIDGE TABLE
CREATE TABLE dashflow_appl.role_permissions (
                                                role_id NUMBER,
                                                permission_id NUMBER,
                                                CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
                                                CONSTRAINT fk_role_permissions_roles FOREIGN KEY (role_id) REFERENCES dashflow_appl.roles(role_id) ON DELETE CASCADE,
                                                CONSTRAINT fk_role_permissions_perms FOREIGN KEY (permission_id) REFERENCES dashflow_appl.permissions(permission_id) ON DELETE CASCADE
);
commit;
-- SEED DATA
-- Using MERGE to handle "ON CONFLICT" behavior

-- ROLES
MERGE INTO dashflow_appl.roles r
USING (
    SELECT 1 AS role_id, 'ROLE_OPERATOR' AS role_name FROM dual UNION ALL
    SELECT 2, 'ROLE_MANAGER' FROM dual UNION ALL
    SELECT 3, 'ROLE_ADMIN' FROM dual
) src
ON (r.role_name = src.role_name)
WHEN NOT MATCHED THEN
INSERT (role_id, role_name) VALUES (src.role_id, src.role_name);

-- PERMISSIONS
MERGE INTO dashflow_appl.permissions p
USING (
    SELECT 1 AS permission_id, 'view_assigned_cards' AS permission_name, 'Visualizar cards atribuídos' AS description FROM dual UNION ALL
    SELECT 2, 'view_cards_by_period', 'Visualizar cards por período' FROM dual UNION ALL
    SELECT 3, 'view_finished_cards', 'Visualizar cards finalizados' FROM dual UNION ALL
    SELECT 4, 'view_cards_by_status', 'Visualizar cards por status' FROM dual UNION ALL
    SELECT 5, 'view_average_execution_time', 'Visualizar tempo médio de execução' FROM dual UNION ALL
    SELECT 6, 'view_projects_participated', 'Visualizar projetos participados' FROM dual UNION ALL
    SELECT 7, 'export_csv', 'Exportar dados para CSV' FROM dual UNION ALL
    SELECT 8, 'view_assigned_cards_count', 'Visualizar quantidade de cards atribuídos' FROM dual UNION ALL
    SELECT 9, 'view_cards_by_employee', 'Visualizar cards por colaborador' FROM dual UNION ALL
    SELECT 10, 'view_created_cards_by_period', 'Visualizar cards criados por período' FROM dual UNION ALL
    SELECT 11, 'view_finished_cards_by_period', 'Visualizar cards finalizados por período' FROM dual UNION ALL
    SELECT 12, 'view_average_execution_time_by_employee', 'Visualizar tempo médio de execução por colaborador' FROM dual UNION ALL
    SELECT 13, 'view_reworked_cards', 'Visualizar cards com retrabalho' FROM dual UNION ALL
    SELECT 14, 'view_issues_by_project', 'Visualizar issues por projeto' FROM dual UNION ALL
    SELECT 15, 'view_cards_by_tags', 'Visualizar cards por tags' FROM dual UNION ALL
    SELECT 16, 'view_total_projects', 'Visualizar quantidade total de projetos' FROM dual UNION ALL
    SELECT 17, 'view_total_issues', 'Visualizar quantidade total de issues' FROM dual UNION ALL
    SELECT 18, 'view_total_cards', 'Visualizar quantidade total de cards' FROM dual UNION ALL
    SELECT 19, 'view_project_manager', 'Visualizar gestor do projeto' FROM dual UNION ALL
    SELECT 20, 'create_api_integration', 'Criar API para integração' FROM dual
) src
ON (p.permission_name = src.permission_name)
WHEN NOT MATCHED THEN
INSERT (permission_id, permission_name, description)
    VALUES (src.permission_id, src.permission_name, src.description);

-- ROLE_PERMISSIONS
-- ROLE_OPERATOR (1)
MERGE INTO dashflow_appl.role_permissions rp
USING (
    SELECT 1 AS role_id, 1 AS permission_id FROM dual UNION ALL
    SELECT 1, 2 FROM dual UNION ALL
    SELECT 1, 3 FROM dual UNION ALL
    SELECT 1, 4 FROM dual UNION ALL
    SELECT 1, 5 FROM dual UNION ALL
    SELECT 1, 6 FROM dual UNION ALL
    SELECT 1, 7 FROM dual
) src
ON (rp.role_id = src.role_id AND rp.permission_id = src.permission_id)
WHEN NOT MATCHED THEN
INSERT (role_id, permission_id) VALUES (src.role_id, src.permission_id);

-- ROLE_MANAGER (2)
MERGE INTO dashflow_appl.role_permissions rp
USING (
    SELECT 2 AS role_id, 8 AS permission_id FROM dual UNION ALL
    SELECT 2, 9 FROM dual UNION ALL
    SELECT 2, 10 FROM dual UNION ALL
    SELECT 2, 11 FROM dual UNION ALL
    SELECT 2, 12 FROM dual UNION ALL
    SELECT 2, 13 FROM dual UNION ALL
    SELECT 2, 14 FROM dual UNION ALL
    SELECT 2, 15 FROM dual UNION ALL
    SELECT 2, 7 FROM dual
) src
ON (rp.role_id = src.role_id AND rp.permission_id = src.permission_id)
WHEN NOT MATCHED THEN
INSERT (role_id, permission_id) VALUES (src.role_id, src.permission_id);

--ROLE_ADMIN (3)
MERGE INTO dashflow_appl.role_permissions rp
USING (
    SELECT 3 as  role_id, 10 as permission_id FROM dual UNION ALL
    SELECT 3, 11 FROM dual UNION ALL
    SELECT 3, 16 FROM dual UNION ALL
    SELECT 3, 17 FROM dual UNION ALL
    SELECT 3, 18 FROM dual UNION ALL
    SELECT 3, 19 FROM dual UNION ALL
    SELECT 3, 20 FROM dual UNION ALL
    SELECT 3, 7 FROM dual
) src
ON (rp.role_id = src.role_id AND rp.permission_id = src.permission_id)
WHEN NOT MATCHED THEN
INSERT (role_id, permission_id) VALUES (src.role_id, src.permission_id);

COMMIT;

-- AUDIT_LOG TABLE
CREATE TABLE dashflow_appl.audit_log (
                                         log_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                         user_id NUMBER,
                                         request_method VARCHAR2(10) NOT NULL,
                                         request_uri VARCHAR2(255) NOT NULL,
                                         response_status NUMBER,
                                         error_message VARCHAR2(255),
                                         timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
                                         CONSTRAINT fk_audit_log_users FOREIGN KEY (user_id) REFERENCES dashflow_appl.users(user_id)
);