name: Java Build and Deploy to Tomcat VM (SCP + SSH Actions)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: dashflow
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/dashflow
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Find WAR file
        id: find-war
        run: |
          WAR_FILE=$(ls target/*.war | head -n 1)
          echo "WAR_FILE=${WAR_FILE}" >> $GITHUB_OUTPUT
          echo "WAR_FILENAME=$(basename ${WAR_FILE})" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy WAR to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.VM_PORT || '22' }}
          source: "target/*.war"
          target: "/tmp/"

      - name: Deploy on Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.VM_PORT || '22' }}
          script: |
            sudo systemctl stop tomcat
            sudo rm -rf /opt/tomcat/webapps/ROOT*
            sudo mv /tmp/*.war /opt/tomcat/webapps/ROOT.war
            sudo chown tomcat:tomcat /opt/tomcat/webapps/ROOT.war
            sudo systemctl start tomcat
            echo "Deployment completed successfully!"